services:
  postgres:
    image: library/postgres
    ports:
      - "5432:5432"
    volumes_from:
      - pgdata
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ten_ex

  pgdata:
    image: busybox
    volumes:
      - /data